/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    ChatHeader: typeof import('./components/chat/ChatHeader.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    MessageItem: typeof import('./components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    Separator: typeof import('./components/ui/separator/Separator.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Tooltip: typeof import('./components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
